### ISSUE TITLE
Invalid JSON when query contains two consecutive NOT Operators

### ISSUE THREAD

**Issue by MirzaHamza00** [jetstreamapp/soql-parser-js#237]
- [ ] Feature
- [x] Bug

## Description
Since SOQL lacks the NOT LIKE operator, the alternative is `NOT City LIKE '%123%'`, and the parser correctly parses it into JSON.
![image](https://github.com/jetstreamapp/soql-parser-js/assets/97656057/13661220-f6c1-454d-9971-6551710176c4)

However, when I attempted to negate the entire query by enclosing it with the NOT operator, the parser treated it as a single entity and returned a JSON with corruption.
![image](https://github.com/jetstreamapp/soql-parser-js/assets/97656057/fa1bc06c-3a9e-4ba0-8074-6c6621f98413)

The placement of "NOT" is causing confusion, as it's unclear whether it belongs to a specific LIKE operator or if it negates the entire query.

**Comment by paustint** [comment]
@MirzaHamza00 - Thank you for reporting this, and there is definitely a bug with this.
I think the latest query you shared is not actually valid

`WHERE NOT (NOT BillingCity LIKE '%123%' AND id = null)` does not run in the dev console, so I think it is invalid to have an AND statement within the parentheses.

I tested with `SELECT Id, BillingCity FROM Account  WHERE NOT (NOT BillingCity LIKE '%123%')` and this produced invalid JSON that could not be composed into a valid query.

If you have any other test-cases that I can test this with, let me know and I can make sure that they work correctly.

I am working on a fix now - and the output will look like this
`SELECT Id, BillingCity FROM Account  WHERE NOT (NOT BillingCity LIKE '%123%')`
```
{
  fields: [
    { type: 'Field', field: 'Id' },
    { type: 'Field', field: 'BillingCity' },
  ],
  sObject: 'Account',
  where: {
    left: null,
    operator: 'NOT',
    right: {
      left: {
        openParen: 1,
      },
      operator: 'NOT',
      right: {
        left: {
          field: 'BillingCity',
          operator: 'LIKE',
          value: `'%123%'`,
          literalType: 'STRING',
          closeParen: 1,
        },
      },
    },
  },
}
```

**Comment by paustint** [comment]
Not the same, but very similar issue https://github.com/jetstreamapp/jetstream/issues/702
