### ISSUE TITLE
Invalid JSON for NOT negation when query contains first condtion having NOT Operators

### ISSUE THREAD

**Issue by MirzaHamza00** [jetstreamapp/soql-parser-js#242]
- [ ] Feature
- [x] Bug

Hi @paustint,
The issue mentioned in the [summary](https://github.com/jetstreamapp/soql-parser-js/issues/237) is functioning properly but there is another scenario related to that. When I add a second condition with any operator with the first condition having the **NOT LIKE** operator and wrapping the whole query in **NOT,** the **JSON** produced by the parser is corrupted.

**Here is the Reference Query**: `Select Id, City from Lead where NOT ((NOT (City LIKE '%LHR%')) AND City LIKE '%KHR%')`

I tested this query on the **Developer Console** and it's working fine there but the generated **JSON** is missing the first **City condition**.
Example 1:
![image](https://github.com/jetstreamapp/soql-parser-js/assets/75535903/ba2df98b-fbba-42c5-88c9-a0853e633321)

Example 2:
![image](https://github.com/jetstreamapp/soql-parser-js/assets/75535903/fd465345-2226-4af6-84a1-16512d893fd4)

**Comment by paustint** [comment]
Thanks for reporting (again) - I didn't have many test-cases for `NOT` so these slipped and they are not used by many people so they were undiscovered (kudos!)

I'll try to take a look in the next couple of days and see if I can get it resolved.

**Comment by paustint** [comment]
`SELECT Id, City FROM Lead WHERE NOT ((NOT (City LIKE '%LHR%')) AND City LIKE '%KHR%')`

is parsed to the following and is successfully composed back to the same initial query.
```json
{
  "fields": [
    {
      "type": "Field",
      "field": "Id"
    },
    {
      "type": "Field",
      "field": "City"
    }
  ],
  "sObject": "Lead",
  "where": {
    "left": null,
    "operator": "NOT",
    "right": {
      "left": {
        "openParen": 2
      },
      "operator": "NOT",
      "right": {
        "left": {
          "field": "City",
          "operator": "LIKE",
          "literalType": "STRING",
          "value": "'%LHR%'",
          "openParen": 1,
          "closeParen": 2
        },
        "operator": "AND",
        "right": {
          "left": {
            "field": "City",
            "operator": "LIKE",
            "literalType": "STRING",
            "value": "'%KHR%'",
            "closeParen": 1
          }
        }
      }
    }
  }
}
```
